### ISSUE TITLE
Your mod Breaks vanilla mineables, tools and tool levels for block

### ISSUE THREAD

**Issue by Rav115** [Starexify/BigSwordsR#1]
Version - big_swords-1.0.1.jar
Forge - 1.20.1-forge-47.3.11

Your mod Breaks vanilla mineables, tools and tool levels for block
jade tooltip shows that you need like diamond level tools for most stuff and some stuff dont even have tool anymore
atleast coal works
![attels](https://github.com/user-attachments/assets/b1b420a6-f38d-48da-80bc-416852070a7a)

**Comment by Starexify** [comment]
Fixed in 1.0.2, thanks 👍
